# syntax = docker/dockerfile:1

# Make sure it matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.4.7
FROM ruby:$RUBY_VERSION-slim as base

# Install the tools we need
RUN apt update && apt install -y zip

# Export from this folder
WORKDIR /labfire

# Copy application code
COPY . .

# Create the archive
CMD ["zip", "-r", "/labfire.zip", "."]
